name: GreensboroLawyer
favicon: null
layout_spectrum: 0.597840727539733
typography_spectrum: 0.31623306358233094
title: >-
  Greensboro North Carolina Attorney Brandon S. Goldsborough Criminal Defense
  Lawyer DWI Speeding traffic misdemeanors felonies drugs theft assault
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.66778459912166
  lightness: 0.9870536488015205
  saturation: 0.6102580318693072
  rhythmicContrast: 0.9844095020089298
purpose: []
