name: Greensboro Lawyer
favicon: null
layout_spectrum: 0.24554
typography_spectrum: 0.45354
title: >-
  Greensboro North Carolina Attorney Brandon S. Goldsborough Criminal Defense
  Lawyer DWI Speeding traffic misdemeanors felonies drugs theft assault
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c0b283'
    - '#f4f4f4'
    - '#373737'
    - '#666666'
    - '#d0d0d0'
  brandStrength: 0.66778459912166
  lightness: 0.9870536488015205
  saturation: 0.6102580318693072
  rhythmicContrast: 0.9844095020089298
purpose: []
